@ECHO off
SET PYTHON_EXECUTABLE="E:\py-virtualenv\autoarchive\Scripts\python.exe"
SET AUTOARCHIVE_SCRIPT="E:\py-projects\autoarchive\autoarchive.py"
SET OUTPUT_DIRECTORY="E:\Output"
SET PROFILE="xdcam"
SET DIRECTORY_DEPTH=1
SET VERBOSITY=1

"%PYTHON_EXECUTABLE%" "%AUTOARCHIVE_SCRIPT%" -v %VERBOSITY% run %1 "%OUTPUT_DIRECTORY%" "%PROFILE%" -dd %DIRECTORY_DEPTH%
PAUSE